library(data.table)

df.MexHigh <- fread("MexHigh_MexLow_parv.frq")
head(df.MexHigh)
df.MexHigh <- as.data.frame(df.MexHigh)
names(df.MexHigh) <- c("chr", "pos", "freqREF_MexHigh", "freqALT_MexHigh", "freqREF_MexLow", "freqALT_MexLow", "freqREF_parv", "freqALT_parv")
df.MexHigh["SNPtypeMexHigh"] <- ifelse(df.MexHigh$freqREF_MexHigh==df.MexHigh$freqREF_MexLow, "noDir", "unknown")
df.MexHigh$SNPtypeMexHigh <- ifelse(df.MexHigh$freqREF_MexHigh > df.MexHigh$freqREF_MexLow, "elevRef", df.MexHigh$SNPtypeMexHigh)
df.MexHigh$SNPtypeMexHigh <- ifelse(df.MexHigh$freqALT_MexHigh > df.MexHigh$freqALT_MexLow, "elevALT", df.MexHigh$SNPtypeMexHigh)
head(df.MexHigh)
subset(df.MexHigh, df.MexHigh$SNPtypeMexHigh=="unknown")
df.MexHigh["ID"] <- paste(df.MexHigh$chr, df.MexHigh$pos, sep="_")

df.GuaHigh <- fread("GuaHigh_MexLow_parv.frq")
head(df.GuaHigh)
df.GuaHigh <- as.data.frame(df.GuaHigh)
names(df.GuaHigh) <- c("chr", "pos", "freqREF_GuaHigh", "freqALT_GuaHigh", "freqREF_MexLow", "freqALT_MexLow", "freqREF_parv", "freqALT_parv")
df.GuaHigh["SNPtypeGuaHigh"] <- ifelse(df.GuaHigh$freqREF_GuaHigh==df.GuaHigh$freqREF_MexLow, "noDir", "unknown")
df.GuaHigh$SNPtypeGuaHigh <- ifelse(df.GuaHigh$freqREF_GuaHigh > df.GuaHigh$freqREF_MexLow, "elevRef", df.GuaHigh$SNPtypeGuaHigh)
df.GuaHigh$SNPtypeGuaHigh <- ifelse(df.GuaHigh$freqALT_GuaHigh > df.GuaHigh$freqALT_MexLow, "elevALT", df.GuaHigh$SNPtypeGuaHigh)
head(df.GuaHigh)
subset(df.GuaHigh, df.GuaHigh$SNPtypeGuaHigh=="unknown")
df.GuaHigh["ID"] <- paste(df.GuaHigh$chr, df.GuaHigh$pos, sep="_")

df.SW_US <- fread("SW_US_MexLow_parv.frq")
head(df.SW_US)
df.SW_US <- as.data.frame(df.SW_US)
names(df.SW_US) <- c("chr", "pos", "freqREF_SW_US", "freqALT_SW_US", "freqREF_MexLow", "freqALT_MexLow", "freqREF_parv", "freqALT_parv")
df.SW_US["SNPtypeSW_US"] <- ifelse(df.SW_US$freqREF_SW_US==df.SW_US$freqREF_MexLow, "noDir", "unknown")
df.SW_US$SNPtypeSW_US <- ifelse(df.SW_US$freqREF_SW_US > df.SW_US$freqREF_MexLow, "elevRef", df.SW_US$SNPtypeSW_US)
df.SW_US$SNPtypeSW_US <- ifelse(df.SW_US$freqALT_SW_US > df.SW_US$freqALT_MexLow, "elevALT", df.SW_US$SNPtypeSW_US)
head(df.SW_US)
subset(df.SW_US, df.SW_US$SNPtypeSW_US=="unknown")
df.SW_US["ID"] <- paste(df.SW_US$chr, df.SW_US$pos, sep="_")

df.Andes <- fread("Andes_SA_Low_parv.frq")
head(df.Andes)
df.Andes <- as.data.frame(df.Andes)
names(df.Andes) <- c("chr", "pos", "freqREF_Andes", "freqALT_Andes", "freqREF_MexLow", "freqALT_MexLow", "freqREF_SA_Low", "freqALT_SA_Low")
df.Andes["SNPtypeAndes"] <- ifelse(df.Andes$freqREF_Andes==df.Andes$freqREF_SA_Low, "noDir", "unknown")
df.Andes$SNPtypeAndes <- ifelse(df.Andes$freqREF_Andes > df.Andes$freqREF_SA_Low, "elevRef", df.Andes$SNPtypeAndes)
df.Andes$SNPtypeAndes <- ifelse(df.Andes$freqALT_Andes > df.Andes$freqALT_SA_Low, "elevALT", df.Andes$SNPtypeAndes)
head(df.Andes)
subset(df.Andes, df.Andes$SNPtypeAndes=="unknown")
df.Andes["ID"] <- paste(df.Andes$chr, df.Andes$pos, sep="_")

##MexHigh vs. GuaHigh
df.MexHigh.GuaHigh <- merge(df.MexHigh, df.GuaHigh, by="ID")
df.MexHigh.GuaHigh["SNPtype"] <- ifelse(df.MexHigh.GuaHigh$SNPtypeMexHigh== "noDir" | df.MexHigh.GuaHigh$SNPtypeGuaHigh=="noDir", "noDir", "unknown")
df.MexHigh.GuaHigh$SNPtype <- ifelse(df.MexHigh.GuaHigh$SNPtypeMexHigh=="elevALT" & df.MexHigh.GuaHigh$SNPtypeGuaHigh=="elevALT", "coDir", df.MexHigh.GuaHigh$SNPtype)
df.MexHigh.GuaHigh$SNPtype <- ifelse(df.MexHigh.GuaHigh$SNPtypeMexHigh=="elevRef" & df.MexHigh.GuaHigh$SNPtypeGuaHigh=="elevRef", "coDir", df.MexHigh.GuaHigh$SNPtype)
df.MexHigh.GuaHigh$SNPtype <- ifelse(df.MexHigh.GuaHigh$SNPtypeMexHigh== "elevALT" & df.MexHigh.GuaHigh$SNPtypeGuaHigh=="elevRef", "antiDir", df.MexHigh.GuaHigh$SNPtype)
df.MexHigh.GuaHigh$SNPtype <- ifelse(df.MexHigh.GuaHigh$SNPtypeMexHigh== "elevRef" & df.MexHigh.GuaHigh$SNPtypeGuaHigh=="elevALT", "antiDir", df.MexHigh.GuaHigh$SNPtype)
write.table(df.MexHigh.GuaHigh[, c(1:7,10,13,14,19,20)], file="MexHigh.GuaHigh.parallel.SNPtype", quote=F, sep="\t", row.names=F)
 
##MexHigh vs. SW_US
df.MexHigh.SW_US <- merge(df.MexHigh, df.SW_US, by="ID")
df.MexHigh.SW_US["SNPtype"] <- ifelse(df.MexHigh.SW_US$SNPtypeMexHigh== "noDir" | df.MexHigh.SW_US$SNPtypeSW_US=="noDir", "noDir", "unknown")
df.MexHigh.SW_US$SNPtype <- ifelse(df.MexHigh.SW_US$SNPtypeMexHigh=="elevALT" & df.MexHigh.SW_US$SNPtypeSW_US=="elevALT", "coDir", df.MexHigh.SW_US$SNPtype)
df.MexHigh.SW_US$SNPtype <- ifelse(df.MexHigh.SW_US$SNPtypeMexHigh=="elevRef" & df.MexHigh.SW_US$SNPtypeSW_US=="elevRef", "coDir", df.MexHigh.SW_US$SNPtype)
df.MexHigh.SW_US$SNPtype <- ifelse(df.MexHigh.SW_US$SNPtypeMexHigh== "elevALT" & df.MexHigh.SW_US$SNPtypeSW_US=="elevRef", "antiDir", df.MexHigh.SW_US$SNPtype)
df.MexHigh.SW_US$SNPtype <- ifelse(df.MexHigh.SW_US$SNPtypeMexHigh== "elevRef" & df.MexHigh.SW_US$SNPtypeSW_US=="elevALT", "antiDir", df.MexHigh.SW_US$SNPtype)
write.table(df.MexHigh.SW_US[, c(1:7,10,13,14,19,20)], file="MexHigh.SW_US.parallel.SNPtype", quote=F, sep="\t", row.names=F)

##MexHigh vs. Andes
df.MexHigh.Andes <- merge(df.MexHigh, df.Andes, by="ID")
df.MexHigh.Andes["SNPtype"] <- ifelse(df.MexHigh.Andes$SNPtypeMexHigh== "noDir" | df.MexHigh.Andes$SNPtypeAndes=="noDir", "noDir", "unknown")
df.MexHigh.Andes$SNPtype <- ifelse(df.MexHigh.Andes$SNPtypeMexHigh=="elevALT" & df.MexHigh.Andes$SNPtypeAndes=="elevALT", "coDir", df.MexHigh.Andes$SNPtype)
df.MexHigh.Andes$SNPtype <- ifelse(df.MexHigh.Andes$SNPtypeMexHigh=="elevRef" & df.MexHigh.Andes$SNPtypeAndes=="elevRef", "coDir", df.MexHigh.Andes$SNPtype)
df.MexHigh.Andes$SNPtype <- ifelse(df.MexHigh.Andes$SNPtypeMexHigh== "elevALT" & df.MexHigh.Andes$SNPtypeAndes=="elevRef", "antiDir", df.MexHigh.Andes$SNPtype)
df.MexHigh.Andes$SNPtype <- ifelse(df.MexHigh.Andes$SNPtypeMexHigh== "elevRef" & df.MexHigh.Andes$SNPtypeAndes=="elevALT", "antiDir", df.MexHigh.Andes$SNPtype)
write.table(df.MexHigh.Andes[, c(1:10,13,14,19,20)], file="MexHigh.Andes.parallel.SNPtype", quote=F, sep="\t", row.names=F)

##SW_US vs. GuaHigh
df.SW_US.GuaHigh <- merge(df.SW_US, df.GuaHigh, by="ID")
df.SW_US.GuaHigh["SNPtype"] <- ifelse(df.SW_US.GuaHigh$SNPtypeSW_US== "noDir" | df.SW_US.GuaHigh$SNPtypeGuaHigh=="noDir", "noDir", "unknown")
df.SW_US.GuaHigh$SNPtype <- ifelse(df.SW_US.GuaHigh$SNPtypeSW_US=="elevALT" & df.SW_US.GuaHigh$SNPtypeGuaHigh=="elevALT", "coDir", df.SW_US.GuaHigh$SNPtype)
df.SW_US.GuaHigh$SNPtype <- ifelse(df.SW_US.GuaHigh$SNPtypeSW_US=="elevRef" & df.SW_US.GuaHigh$SNPtypeGuaHigh=="elevRef", "coDir", df.SW_US.GuaHigh$SNPtype)
df.SW_US.GuaHigh$SNPtype <- ifelse(df.SW_US.GuaHigh$SNPtypeSW_US== "elevALT" & df.SW_US.GuaHigh$SNPtypeGuaHigh=="elevRef", "antiDir", df.SW_US.GuaHigh$SNPtype)
df.SW_US.GuaHigh$SNPtype <- ifelse(df.SW_US.GuaHigh$SNPtypeSW_US== "elevRef" & df.SW_US.GuaHigh$SNPtypeGuaHigh=="elevALT", "antiDir", df.SW_US.GuaHigh$SNPtype)
write.table(df.SW_US.GuaHigh[, c(1:7,10,13,14,19,20)], file="SW_US.GuaHigh.parallel.SNPtype", quote=F, sep="\t", row.names=F)

##Andes vs. GuaHigh
df.Andes.GuaHigh <- merge(df.Andes, df.GuaHigh, by="ID")
df.Andes.GuaHigh["SNPtype"] <- ifelse(df.Andes.GuaHigh$SNPtypeAndes== "noDir" | df.Andes.GuaHigh$SNPtypeGuaHigh=="noDir", "noDir", "unknown")
df.Andes.GuaHigh$SNPtype <- ifelse(df.Andes.GuaHigh$SNPtypeAndes=="elevALT" & df.Andes.GuaHigh$SNPtypeGuaHigh=="elevALT", "coDir", df.Andes.GuaHigh$SNPtype)
df.Andes.GuaHigh$SNPtype <- ifelse(df.Andes.GuaHigh$SNPtypeAndes=="elevRef" & df.Andes.GuaHigh$SNPtypeGuaHigh=="elevRef", "coDir", df.Andes.GuaHigh$SNPtype)
df.Andes.GuaHigh$SNPtype <- ifelse(df.Andes.GuaHigh$SNPtypeAndes== "elevALT" & df.Andes.GuaHigh$SNPtypeGuaHigh=="elevRef", "antiDir", df.Andes.GuaHigh$SNPtype)
df.Andes.GuaHigh$SNPtype <- ifelse(df.Andes.GuaHigh$SNPtypeAndes== "elevRef" & df.Andes.GuaHigh$SNPtypeGuaHigh=="elevALT", "antiDir", df.Andes.GuaHigh$SNPtype)
write.table(df.Andes.GuaHigh[, c(1:10,13,14,19,20)], file="Andes.GuaHigh.parallel.SNPtype", quote=F, sep="\t", row.names=F)

##Andes vs. SW_US
df.Andes.SW_US <- merge(df.Andes, df.SW_US, by="ID")
df.Andes.SW_US["SNPtype"] <- ifelse(df.Andes.SW_US$SNPtypeAndes== "noDir" | df.Andes.SW_US$SNPtypeSW_US=="noDir", "noDir", "unknown")
df.Andes.SW_US$SNPtype <- ifelse(df.Andes.SW_US$SNPtypeAndes=="elevALT" & df.Andes.SW_US$SNPtypeSW_US=="elevALT", "coDir", df.Andes.SW_US$SNPtype)
df.Andes.SW_US$SNPtype <- ifelse(df.Andes.SW_US$SNPtypeAndes=="elevRef" & df.Andes.SW_US$SNPtypeSW_US=="elevRef", "coDir", df.Andes.SW_US$SNPtype)
df.Andes.SW_US$SNPtype <- ifelse(df.Andes.SW_US$SNPtypeAndes== "elevALT" & df.Andes.SW_US$SNPtypeSW_US=="elevRef", "antiDir", df.Andes.SW_US$SNPtype)
df.Andes.SW_US$SNPtype <- ifelse(df.Andes.SW_US$SNPtypeAndes== "elevRef" & df.Andes.SW_US$SNPtypeSW_US=="elevALT", "antiDir", df.Andes.SW_US$SNPtype)
write.table(df.Andes.SW_US[, c(1:10,13,14,19,20)], file="Andes.SW_US.parallel.SNPtype", quote=F, sep="\t", row.names=F)
