library(data.table)


outlier <- fread("MexHigh.GuaHigh.common.outlierPBE.txt")
outlier <- as.data.frame(outlier)
df <- fread("MexHigh.GuaHigh.parallel.SNPtype")
df <- as.data.frame(df)
head(df)
head(outlier)
outlier["ID"] <- paste(outlier$V1, outlier$V2, sep="_")
df.outlier <- merge(df, outlier, by="ID")
length(df.outlier$ID)
table(df.outlier$SNPtype)
neutral <- fread("MexHigh.GuaHigh.neutralPBE.txt")
neutral <- as.data.frame(neutral)
neutral["ID"] <- paste(neutral$V1, neutral$V2, sep="_")
head(neutral)
df.neutral <- merge(df, neutral, by="ID")
table(df.neutral$SNPtype)
names(df.outlier)
write.table(df.outlier[, 1:12], file="MexHigh.GuaHigh.outlier.SNPtype", quote=F, sep="\t", row.names=F )

outlier <- fread("MexHigh.SW_US.common.outlierPBE.txt")
outlier <- as.data.frame(outlier)
df <- fread("MexHigh.SW_US.parallel.SNPtype")
df <- as.data.frame(df)
head(df)
head(outlier)
outlier["ID"] <- paste(outlier$V1, outlier$V2, sep="_")
df.outlier <- merge(df, outlier, by="ID")
length(df.outlier$ID)
table(df.outlier$SNPtype)
neutral <- fread("MexHigh.SW_US.neutralPBE.txt")
neutral <- as.data.frame(neutral)
neutral["ID"] <- paste(neutral$V1, neutral$V2, sep="_")
head(neutral)
df.neutral <- merge(df, neutral, by="ID")
table(df.neutral$SNPtype)
names(df.outlier)
write.table(df.outlier[, 1:12], file="MexHigh.SW_US.outlier.SNPtype", quote=F, sep="\t", row.names=F )

outlier <- fread("MexHigh.Andes.common.outlierPBE.txt")
outlier <- as.data.frame(outlier)
df <- fread("MexHigh.Andes.parallel.SNPtype")
df <- as.data.frame(df)
head(df)
head(outlier)
outlier["ID"] <- paste(outlier$V1, outlier$V2, sep="_")
df.outlier <- merge(df, outlier, by="ID")
length(df.outlier$ID)
table(df.outlier$SNPtype)
neutral <- fread("MexHigh.Andes.neutralPBE.txt")
neutral <- as.data.frame(neutral)
neutral["ID"] <- paste(neutral$V1, neutral$V2, sep="_")
head(neutral)
df.neutral <- merge(df, neutral, by="ID")
table(df.neutral$SNPtype)
names(df.outlier)
write.table(df.outlier[, 1:14], file="MexHigh.Andes.outlier.SNPtype", quote=F, sep="\t", row.names=F )

outlier <- fread("SW_US.GuaHigh.common.outlierPBE.txt")
outlier <- as.data.frame(outlier)
df <- fread("SW_US.GuaHigh.parallel.SNPtype")
df <- as.data.frame(df)
head(df)
head(outlier)
outlier["ID"] <- paste(outlier$V1, outlier$V2, sep="_")
df.outlier <- merge(df, outlier, by="ID")
length(df.outlier$ID)
table(df.outlier$SNPtype)
neutral <- fread("SW_US.GuaHigh.neutralPBE.txt")
neutral <- as.data.frame(neutral)
neutral["ID"] <- paste(neutral$V1, neutral$V2, sep="_")
head(neutral)
df.neutral <- merge(df, neutral, by="ID")
table(df.neutral$SNPtype)
names(df.outlier)
write.table(df.outlier[, 1:12], file="SW_US.GuaHigh.outlier.SNPtype", quote=F, sep="\t", row.names=F )

outlier <- fread("Andes.GuaHigh.common.outlierPBE.txt")
outlier <- as.data.frame(outlier)
df <- fread("Andes.GuaHigh.parallel.SNPtype")
df <- as.data.frame(df)
head(df)
head(outlier)
outlier["ID"] <- paste(outlier$V1, outlier$V2, sep="_")
df.outlier <- merge(df, outlier, by="ID")
length(df.outlier$ID)
table(df.outlier$SNPtype)
neutral <- fread("Andes.GuaHigh.neutralPBE.txt")
neutral <- as.data.frame(neutral)
neutral["ID"] <- paste(neutral$V1, neutral$V2, sep="_")
head(neutral)
df.neutral <- merge(df, neutral, by="ID")
table(df.neutral$SNPtype)
names(df.outlier)
write.table(df.outlier[, 1:14], file="Andes.GuaHigh.outlier.SNPtype", quote=F, sep="\t", row.names=F )

outlier <- fread("Andes.SW_US.common.outlierPBE.txt")
outlier <- as.data.frame(outlier)
df <- fread("Andes.SW_US.parallel.SNPtype")
df <- as.data.frame(df)
head(df)
head(outlier)
outlier["ID"] <- paste(outlier$V1, outlier$V2, sep="_")
df.outlier <- merge(df, outlier, by="ID")
length(df.outlier$ID)
table(df.outlier$SNPtype)
neutral <- fread("Andes.SW_US.neutralPBE.txt")
neutral <- as.data.frame(neutral)
neutral["ID"] <- paste(neutral$V1, neutral$V2, sep="_")
head(neutral)
df.neutral <- merge(df, neutral, by="ID")
table(df.neutral$SNPtype)
names(df.outlier)
write.table(df.outlier[, 1:14], file="Andes.SW_US.outlier.SNPtype", quote=F, sep="\t", row.names=F )
