#!/bin/bash
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --time=96:00:00
#SBATCH --job-name=R
#SBATCH --output=R_%j.out 
#SBATCH --error=R_%j.err
#SBATCH --mail-user=lilepisorus@gmail.com   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END

cd $SLURM_SUBMIT_DIR
ulimit -s unlimited
module load vcftools
module load tabix

./vep.new.sh MexHigh.GuaHigh
./vep.new.sh MexHigh.SW_US
./vep.new.sh MexHigh.Andes
./vep.Andes.sh Andes.GuaHigh
./vep.Andes.sh Andes.SW_US
./vep.GuaHigh.sh SW_US.GuaHigh

#ssh condo "qstat -f ${SLURM_JOB_ID} |head"

